version: '3.8'
services:
  mysql:
    image: mysql:8.0
    container_name: demo-mysql
    environment:
      MYSQL_ROOT_PASSWORD: 21258era#met
      MYSQL_DATABASE: cicd
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysql", "-h", "localhost", "-u", "root", "-p21258era#met", "-e", "SELECT 1"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s
    networks:
      - app-network
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: kubeeranga118/new_cicd_integration:latest
    container_name: demo-app
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://172.18.0.2:3306/cicd?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 21258era#met
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: com.mysql.cj.jdbc.Driver
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_DATASOURCE_HIKARI_CONNECTION_TEST_QUERY: SELECT 1
      SPRING_DATASOURCE_HIKARI_CONNECTION_INIT_SQL: SELECT 1
      SPRING_DATASOURCE_HIKARI_MAXIMUM_POOL_SIZE: 10
      SPRING_DATASOURCE_HIKARI_MINIMUM_IDLE: 5
      SERVER_ADDRESS: 0.0.0.0
      SERVER_PORT: 8080
    ports:
      - "8881:8080"
    networks:
      - app-network
networks:
  app-network:
    driver: bridge
volumes:
  db_data: